language: node_js
node_js:
  - $TRAVIS_NODE_VERSION

os:
  - linux
  - osx
  - windows

cache:
  npm: true
  directories:
    - node_modules
    - .next

install:
    - npm install

script:
    - npm run lint
